# see https://github.com/pablode/USD/blob/v22.11-ci/.github/workflows/deploy-release.yml
# https://github.com/usd-wg/assets/pull/49
# https://github.com/usd-wg/assets/pull/48 

# About Ubuntu-Latest
# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
# https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md

# About Cache Actions
# https://github.com/marketplace/actions/cache


name: Build Linux

on:
  push:
    branches: [ "main", "gha_dev" ]
  pull_request:
    branches: [ "main" ]
      
jobs:
  build:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      #### ---------  CHECKOUT THIS REPO IF WILL USE SCRIPTS FROM IT -----------
      - name: Checkout This Repo
        uses: actions/checkout@v3
      #### --------------------------  IMAGE SET UP ----------------------------
      # TODO: https://github.com/marketplace/actions/cache-anything-new ?
      - name: Update apt-get 
        run: sudo apt-get update
      # Ubuntu latest has much of what is needed.
      # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
      # Still needed OpenGL
      - name: Set up packages (Linux)
        run: |
          sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev
      # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install install PyOpenGL
          pip install PySide6==6.4.3
          pip install numpy
      #### --------------------------  USD SET UP ------------------------------
      # - name: Restore OpenUSD (Repo and Build)
      #   id: cache-openusd-restore
      #   uses: actions/cache/restore@v3
      #   with:
      #     path: |
      #       OpenUSD_REPO
      #       OpenUSD_BUILD
      #     key: ${{ runner.os }}-openusd
      - name: Clone Pixar USD
        # if: steps.cache-openusd-restore.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: PixarAnimationStudios/OpenUSD
          ## The branch, tag or SHA to checkout.
          # ref: 
          ## Relative path __under $GITHUB_WORKSPACE __ to place the repository
          ## This appears to be a litteral. Cannot take $GITHUB_ENV variable.
          path: OpenUSD_REPO
      - name: Add Repo Loaction to GITHUB_ENV
        # if: steps.cache-openusd-restore.outputs.cache-hit != 'true'
        run: |
          echo "USD_REPO_DIR=$PWD/OpenUSD_REPO" >> $GITHUB_ENV
          echo "-----"
          pwd  
          ls
          which python3
          python3 --version
          which python
          python --version
          echo $GITHUB_WORKSPACE
          echo $PATH
          echo $GITHUB_ENV
          echo "-----"
      - name: Build USD (no python)
        # if: steps.cache-openusd-restore.outputs.cache-hit != 'true'
        run: |
          python $USD_REPO_DIR/build_scripts/build_usd.py OpenUSD_BUILD
          echo "USD_BUILD_DIR=$PWD/OpenUSD_BUILD" >> $GITHUB_ENV
      - name: Confirms Runs
        # if: steps.cache-openusd-restore.outputs.cache-hit != 'true'
        run: |
            $USD_BUILD_DIR/bin/usdcat -h
      # - name: Save OpenUSD Cache (Repo & Build)
      #   id: cache-openusd-save
      #   uses: actions/cache/save@v3
      #   with:
      #     path: |
      #       OpenUSD_REPO
      #       OpenUSD_BUILD
      #     key: ${{ steps.cache-openusd-restore.outputs.cache-primary-key }}   
      ## $GITHUB_PATH update works only for NEXT step
      ## https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-system-path
      - name: Add OpenUSD Build to PATH and PYTHONPATH
        run: |
          export PYTHONPATH=$PYTHONPATH:$USD_BUILD_DIR/lib/python 
          echo "$USD_BUILD_DIR/bin" >> $GITHUB_PATH
          echo "PYTHONPATH=$PYTHONPATH" >> $GITHUB_ENV
      - name: Confirm in Path
        run: |
          echo "----- START Did it work?"
          echo $USD_BUILD_DIR
          echo $PYTHONPATH
          echo $PATH
          echo $GITHUB_PATH
          echo $GITHUB_ENV
          echo "-----"
          usdcat -h
          usdview -h
      #### ----------------------  REPO SPECIFIC CODE --------------------------
      ## If did not check out repo already, do so now. 