# see https://github.com/pablode/USD/blob/v22.11-ci/.github/workflows/deploy-release.yml
# https://github.com/usd-wg/assets/pull/49
# https://github.com/usd-wg/assets/pull/48 

# About Ubuntu-Latest
# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
# https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md

# About Cache Actions
# https://github.com/marketplace/actions/cache
name: Build Linux

on:
  push:
    branches: [ "main", "gha_dev" ]
  pull_request:
    branches: [ "main" ]
      
jobs:
  server-setup:
    name: Do Setup
  build:
    name: Build Linux
    needs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout This Repo
        uses: actions/checkout@v3  
      - name: Confirms USD Runs at Expected Location
        if: steps.cache-openusd-restore.outputs.cache-hit != 'true'
        run: |
            $USD_BUILD_DIR/bin/usdcat -h
