on: [workflow_dispatch]

jobs:
  build:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Update apt-get 
        run: sudo apt-get update
      # Ubuntu latest has much of what is needed.
      # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
      # Still needed OpenGL
      # TODO: https://github.com/marketplace/actions/cache-anything-new ?
      - name: Set up packages (Linux)
        run: |
          sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev
      - name: Restore OpenUSD (Repo and Build)
        id: cache-openusd-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            OpenUSD_REPO
            OpenUSD_BUILD
          key: ${{ runner.os }}-openusd
      - name: Clone Pixar USD
        if: steps.cache-openusd-restore.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: PixarAnimationStudios/OpenUSD
          ## The branch, tag or SHA to checkout.
          # ref: 
          ## Relative path __under $GITHUB_WORKSPACE __ to place the repository
          ## This appears to be a litteral. Cannot take $GITHUB_ENV variable.
          path: OpenUSD_REPO
      - name: Add Repo Loaction to GITHUB_ENV
        if: steps.cache-openusd-restore.outputs.cache-hit != 'true'
        run: |
          echo "USD_REPO_DIR=$PWD/OpenUSD_REPO" >> $GITHUB_ENV
          echo "-----"
          pwd  
          ls
          which python3
          python3 --version
          which python
          python --version
          echo $GITHUB_WORKSPACE
          echo $PATH
          echo $GITHUB_ENV
          echo "-----"
      - name: Build USD (no python)
        if: steps.cache-openusd-restore.outputs.cache-hit != 'true'
        run: |
          python3 $USD_REPO_DIR/build_scripts/build_usd.py --no-python --no-materialx OpenUSD_BUILD
          echo "USD_BUILD_DIR=$PWD/OpenUSD_BUILD" >> $GITHUB_ENV
      - name: Confirms Runs
        if: steps.cache-openusd-restore.outputs.cache-hit != 'true'
        run: |
            $USD_BUILD_DIR/bin/usdcat -h
      - name: Save OpenUSD Cache (Repo & Build)
        id: cache-openusd-save
        uses: actions/cache/save@v3
        with:
          path: |
            OpenUSD_REPO
            OpenUSD_BUILD
          key: ${{ steps.cache-openusd-restore.outputs.cache-primary-key }}   
      ## $GITHUB_PATH update works only for NEXT step
      ## https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-system-path
      - name: Add OpenUSD Build to PATH and PYTHONPATH
        run: |
          export PYTHONPATH=$PYTHONPATH:$USD_BUILD_DIR/lib/pythonecho 
          echo "$USD_BUILD_DIR/bin" >> $GITHUB_PATH
          echo "PYTHONPATH=$PYTHONPATH" >> $GITHUB_ENV
      - name: Confirm in Path
        run: |
          echo "----- START Did it work?"
          echo $USD_BUILD_DIR
          echo $PYTHONPATH
          echo $PATH
          echo $GITHUB_PATH
          echo "-----"
          usdcat -h
